### PR TITLE
release: v1.0.0a11

### PR DESCRIPTION
**Pull request by hachreak**
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

### CODE REVIEW

**Comment by drjova** [comment]
@lnielsen this one has your user https://github.com/inveniosoftware/invenio-previewer/blob/master/.travis.yml#L78 do we need to change this one as well?

**Comment by lnielsen** [comment]
Yep, all of them should use ``inveniosoftware`` user instead of personal account, however, I'd think it's easier to automate it since we have 60 repos to fix.

**Comment by hachreak** [comment]
ping @lnielsen @drjova 
Could you send me the new key for travis? thanks :smile:

**Comment by hachreak** [comment]
ping @drjova @lnielsen

**Pull request merged**
